name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Bump version, push tag
      id: tags
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create project folder
      run: cmake -E make_directory proj

    - name: Configure
      working-directory: ${{github.workspace}}\proj
      run: cmake ../ -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_VERSION="v${{ steps.tags.outputs.new_version }}"

    - name: Build
      working-directory: ${{github.workspace}}\proj
      run: cmake --build . --config MinSizeRel

    - name: Where the hell are my files going
      run: dir "proj\build\MinSizeRel"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.tags.outputs.changelog }}
        tag_name: v${{ steps.tags.outputs.new_version }}
        name: "v${{ steps.tags.outputs.new_version }} - Automatic build"
        prerelease: true
        files: proj\build\MinSizeRel\crosscord.exe