name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Create project folder
      run: cmake -E make_directory ${{github.workspace}}/proj

    - name: Configure
      working-directory: ${{github.workspace}}/proj
      run: cmake ../ -DCMAKE_BUILD_TYPE=MinSizeRel

    - name: Build
      working-directory: ${{github.workspace}}/proj
      run: cmake --build . --config MinSizeRel

    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
      working-directory: ${{github.workspace}}/proj/build/MinSizeRel
      run: gh release create latest --repo=${GITHUB_REF_NAME} --title="Automated build" crosscord.exe --generate-notes