name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Bump version, push tag
      id: tags
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create project folder
      run: cmake -E make_directory ${{github.workspace}}/proj

    - name: Configure
      working-directory: ${{github.workspace}}/proj
      run: cmake ../ -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_VERSION="v${{ steps.tags.outputs.new_version }}"

    - name: Build
      working-directory: ${{github.workspace}}/proj
      run: cmake --build . --config MinSizeRel

    - name: Release draft
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        title: "v${{ steps.tags.outputs.new_version }} - Automatic build"
        automatic_release_tag: ${{ steps.tags.outputs.new_tag  }}
        files: ${{github.workspace}}/proj/build/MinSizeRel/crosscord.exe